### GET - Listar produtos
GET http://localhost:3000/produtos
Content-Type: application/json

###

### POST - Criando um novo produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "id": "1",
    "nome": "Hamburguer de frango",
    "preco": 25.00
}

###

### GET por id - Buscar produto pelo id
GET http://localhost:3000/produto/3
Content-Type: application/json

###